- name: Install oh-my-zsh
  block:

  - name: Check .oh-my-zsh
    stat:
      path: ~/.oh-my-zsh
    register: omz_dir

  - name: Run oh-my-zsh install.sh
    command: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    environment:
      KEEP_ZSHRC: "yes"  # don't change .zshrc
      RUNZSH: "no"  # don't launch zsh
      CHSH: "yes"  # do make zsh the default
    when: not omz_dir.stat.exists
    changed_when: true

  become: false
